version: "3"

networks:
  laravel_net:
    driver: bridge

volumes:
  laravel_db:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env.docker
    ports: 
      - 8080:8080
    volumes:
      - ./:/var/www/html
    networks: 
      - laravel_net

  db:
    image: postgres:10.1-alpine
    networks:
      - laravel_net
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports: 
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped